/* This file is automatically generated with "make global". DO NOT EDIT */

extern int fuzzy_basis;
extern int delete_excluded;
extern int stdout_format_has_i;
extern char* sockopts;
extern int copy_unsafe_links;
extern char* logfile_format;
extern int need_messages_from_generator;
extern char* batch_name;
extern int io_filesfrom_buflen;
extern int preserve_executability;
extern int copy_dest;
extern int dry_run;
extern char* dest_option;
extern int compare_dest;
extern int do_xfers;
extern long block_size;
extern int prune_empty_dirs;
extern int am_generator;
extern int remote_protocol;
extern int no_flush;
extern int curr_dir_depth;
extern int sock_f_in;
extern int iobuf_out_cnt;
extern int am_sender;
extern int do_compression;
extern int io_error;
extern int msg_fd_out;
extern int kluge_around_eof;
extern int logfile_format_has_i;
extern int numeric_ids;
extern int log_before_transfer;
extern int max_delete;
extern int defer_forwarding_messages;
extern int io_timeout;
extern int protocol_version;
extern int cvs_exclude;
extern int preserve_links;
extern char* io_filesfrom_bp;
extern int am_server;
extern char io_filesfrom_lastchar;
extern int recurse;
extern int quiet;
extern int verbose;
extern int cleanup_got_literal;
extern int eol_nulls;
extern int whole_file;
extern int preserve_devices;
extern int default_af_hint;
extern int safe_symlinks;
extern int preserve_uid;
extern int delay_updates;
extern int sparse_files;
extern int implied_dirs;
extern char* iobuf_out;
extern char io_filesfrom_buf[2048];
extern char* password_file;
extern unsigned int backup_dir_remainder;
extern int do_progress;
extern struct filter_list_struct filter_list;
extern int copy_links;
extern char curr_dir[MAXPATHLEN];
extern int batch_fd;
extern int local_server;
extern int link_dest;
extern int am_starting_up;
extern char* backup_suffix;
extern int io_multiplexing_out;
extern int msg_fd_in;
extern int ignore_errors;
extern char backup_dir_buf[MAXPATHLEN];
extern int filesfrom_fd;
extern struct filter_list_struct server_filter_list;
extern int always_checksum;
extern int human_readable;
extern int write_batch_monitor_in;
extern int io_multiplexing_in;
extern int preserve_gid;
extern char* iobuf_in;
extern char* shell_cmd;
extern int delete_during;
extern int backup_dir_len;
extern int omit_dir_times;
extern int rsync_port;
extern int modify_window;
extern int batch_dev_null;
extern int preserve_times;
extern int ignore_times;
extern char* stdout_format;
extern int make_backups;
extern int select_timeout;
extern char* filesfrom_host;
extern int update_only;
extern unsigned int file_struct_len;
extern int new_root_dir;
extern int daemon_bwlimit;
extern int sanitize_paths;
extern int xfer_dirs;
extern unsigned int curr_dir_len;
extern int do_stats;
extern char* rsync_path;
extern int list_only;
extern char* partial_dir;
extern int io_filesfrom_f_out;
extern int inplace;
extern int ignore_non_existing;
extern struct filter_list_struct cvs_filter_list;
extern struct stats stats;
extern int delete_mode;
extern int relative_paths;
extern int io_filesfrom_f_in;
extern int write_batch;
extern int allowed_lull;
extern struct file_list* the_file_list;
extern int active_filecnt;
extern int one_file_system;
extern char* backup_dir;
extern int blocking_io;
extern int def_compress_level;
extern int am_root;
extern int preserve_specials;
extern int stdout_format_has_o_or_i;
extern int size_only;
extern int preserve_perms;
extern int backup_suffix_len;
extern int keep_partial;
extern int output_motd;
extern int checksum_seed;
extern int daemon_over_rsh;
extern int remove_source_files;
extern int sock_f_out;
extern int delete_before;
extern int csum_length;
extern int checksum_len;
extern char* logfile_name;
extern int ignore_existing;
extern int batch_gen_fd;
extern char* bind_address;
extern int keep_dirlinks;
extern int force_delete;
extern int logfile_format_has_o_or_i;
extern int am_daemon;
extern char* files_from;
extern int preserve_hard_links;
extern char* tmpdir;
extern int updating_basis_file;
extern int log_got_error;
extern int copy_dirlinks;
extern struct chmod_mode_struct* chmod_modes;
extern int write_batch_monitor_out;
extern int ignore_timeout;
extern int append_mode;
extern char* config_file;
extern int no_detach;
extern int basis_dir_cnt;
extern int delete_after;
extern int read_batch;
extern int bwlimit;

const struct var_info_t global_var_info[] = {
{ &fuzzy_basis, 0, sizeof(fuzzy_basis) },
{ &delete_excluded, 0, sizeof(delete_excluded) },
{ &stdout_format_has_i, 0, sizeof(stdout_format_has_i) },
{ &sockopts, 1, 0 },
{ &copy_unsafe_links, 0, sizeof(copy_unsafe_links) },
{ &logfile_format, 1, 0 },
{ &need_messages_from_generator, 0, sizeof(need_messages_from_generator) },
{ &batch_name, 1, 0 },
{ &io_filesfrom_buflen, 0, sizeof(io_filesfrom_buflen) },
{ &preserve_executability, 0, sizeof(preserve_executability) },
{ &copy_dest, 0, sizeof(copy_dest) },
{ &dry_run, 0, sizeof(dry_run) },
{ &dest_option, 1, 0 },
{ &compare_dest, 0, sizeof(compare_dest) },
{ &do_xfers, 0, sizeof(do_xfers) },
{ &block_size, 0, sizeof(block_size) },
{ &prune_empty_dirs, 0, sizeof(prune_empty_dirs) },
{ &am_generator, 0, sizeof(am_generator) },
{ &remote_protocol, 0, sizeof(remote_protocol) },
{ &no_flush, 0, sizeof(no_flush) },
{ &curr_dir_depth, 0, sizeof(curr_dir_depth) },
{ &sock_f_in, 0, sizeof(sock_f_in) },
{ &iobuf_out_cnt, 0, sizeof(iobuf_out_cnt) },
{ &am_sender, 0, sizeof(am_sender) },
{ &do_compression, 0, sizeof(do_compression) },
{ &io_error, 0, sizeof(io_error) },
{ &msg_fd_out, 0, sizeof(msg_fd_out) },
{ &kluge_around_eof, 0, sizeof(kluge_around_eof) },
{ &logfile_format_has_i, 0, sizeof(logfile_format_has_i) },
{ &numeric_ids, 0, sizeof(numeric_ids) },
{ &log_before_transfer, 0, sizeof(log_before_transfer) },
{ &max_delete, 0, sizeof(max_delete) },
{ &defer_forwarding_messages, 0, sizeof(defer_forwarding_messages) },
{ &io_timeout, 0, sizeof(io_timeout) },
{ &protocol_version, 0, sizeof(protocol_version) },
{ &cvs_exclude, 0, sizeof(cvs_exclude) },
{ &preserve_links, 0, sizeof(preserve_links) },
{ &io_filesfrom_bp, 1, 0 },
{ &am_server, 0, sizeof(am_server) },
{ &io_filesfrom_lastchar, 0, sizeof(io_filesfrom_lastchar) },
{ &recurse, 0, sizeof(recurse) },
{ &quiet, 0, sizeof(quiet) },
{ &verbose, 0, sizeof(verbose) },
{ &cleanup_got_literal, 0, sizeof(cleanup_got_literal) },
{ &eol_nulls, 0, sizeof(eol_nulls) },
{ &whole_file, 0, sizeof(whole_file) },
{ &preserve_devices, 0, sizeof(preserve_devices) },
{ &default_af_hint, 0, sizeof(default_af_hint) },
{ &safe_symlinks, 0, sizeof(safe_symlinks) },
{ &preserve_uid, 0, sizeof(preserve_uid) },
{ &delay_updates, 0, sizeof(delay_updates) },
{ &sparse_files, 0, sizeof(sparse_files) },
{ &implied_dirs, 0, sizeof(implied_dirs) },
{ &iobuf_out, 1, 0 },
{ &io_filesfrom_buf, 0, sizeof(io_filesfrom_buf) },
{ &password_file, 1, 0 },
{ &backup_dir_remainder, 0, sizeof(backup_dir_remainder) },
{ &do_progress, 0, sizeof(do_progress) },
{ &filter_list, 0, sizeof(filter_list) },
{ &copy_links, 0, sizeof(copy_links) },
{ &curr_dir, 0, sizeof(curr_dir) },
{ &batch_fd, 0, sizeof(batch_fd) },
{ &local_server, 0, sizeof(local_server) },
{ &link_dest, 0, sizeof(link_dest) },
{ &am_starting_up, 0, sizeof(am_starting_up) },
{ &backup_suffix, 1, 0 },
{ &io_multiplexing_out, 0, sizeof(io_multiplexing_out) },
{ &msg_fd_in, 0, sizeof(msg_fd_in) },
{ &ignore_errors, 0, sizeof(ignore_errors) },
{ &backup_dir_buf, 0, sizeof(backup_dir_buf) },
{ &filesfrom_fd, 0, sizeof(filesfrom_fd) },
{ &server_filter_list, 0, sizeof(server_filter_list) },
{ &always_checksum, 0, sizeof(always_checksum) },
{ &human_readable, 0, sizeof(human_readable) },
{ &write_batch_monitor_in, 0, sizeof(write_batch_monitor_in) },
{ &io_multiplexing_in, 0, sizeof(io_multiplexing_in) },
{ &preserve_gid, 0, sizeof(preserve_gid) },
{ &iobuf_in, 1, 0 },
{ &shell_cmd, 1, 0 },
{ &delete_during, 0, sizeof(delete_during) },
{ &backup_dir_len, 0, sizeof(backup_dir_len) },
{ &omit_dir_times, 0, sizeof(omit_dir_times) },
{ &rsync_port, 0, sizeof(rsync_port) },
{ &modify_window, 0, sizeof(modify_window) },
{ &batch_dev_null, 0, sizeof(batch_dev_null) },
{ &preserve_times, 0, sizeof(preserve_times) },
{ &ignore_times, 0, sizeof(ignore_times) },
{ &stdout_format, 1, 0 },
{ &make_backups, 0, sizeof(make_backups) },
{ &select_timeout, 0, sizeof(select_timeout) },
{ &filesfrom_host, 1, 0 },
{ &update_only, 0, sizeof(update_only) },
{ &file_struct_len, 0, sizeof(file_struct_len) },
{ &new_root_dir, 0, sizeof(new_root_dir) },
{ &daemon_bwlimit, 0, sizeof(daemon_bwlimit) },
{ &sanitize_paths, 0, sizeof(sanitize_paths) },
{ &xfer_dirs, 0, sizeof(xfer_dirs) },
{ &curr_dir_len, 0, sizeof(curr_dir_len) },
{ &do_stats, 0, sizeof(do_stats) },
{ &rsync_path, 1, 0 },
{ &list_only, 0, sizeof(list_only) },
{ &partial_dir, 1, 0 },
{ &io_filesfrom_f_out, 0, sizeof(io_filesfrom_f_out) },
{ &inplace, 0, sizeof(inplace) },
{ &ignore_non_existing, 0, sizeof(ignore_non_existing) },
{ &cvs_filter_list, 0, sizeof(cvs_filter_list) },
{ &stats, 0, sizeof(stats) },
{ &delete_mode, 0, sizeof(delete_mode) },
{ &relative_paths, 0, sizeof(relative_paths) },
{ &io_filesfrom_f_in, 0, sizeof(io_filesfrom_f_in) },
{ &write_batch, 0, sizeof(write_batch) },
{ &allowed_lull, 0, sizeof(allowed_lull) },
{ &the_file_list, 1, sizeof(*the_file_list) },
{ &active_filecnt, 0, sizeof(active_filecnt) },
{ &one_file_system, 0, sizeof(one_file_system) },
{ &backup_dir, 1, 0 },
{ &blocking_io, 0, sizeof(blocking_io) },
{ &def_compress_level, 0, sizeof(def_compress_level) },
{ &am_root, 0, sizeof(am_root) },
{ &preserve_specials, 0, sizeof(preserve_specials) },
{ &stdout_format_has_o_or_i, 0, sizeof(stdout_format_has_o_or_i) },
{ &size_only, 0, sizeof(size_only) },
{ &preserve_perms, 0, sizeof(preserve_perms) },
{ &backup_suffix_len, 0, sizeof(backup_suffix_len) },
{ &keep_partial, 0, sizeof(keep_partial) },
{ &output_motd, 0, sizeof(output_motd) },
{ &checksum_seed, 0, sizeof(checksum_seed) },
{ &daemon_over_rsh, 0, sizeof(daemon_over_rsh) },
{ &remove_source_files, 0, sizeof(remove_source_files) },
{ &sock_f_out, 0, sizeof(sock_f_out) },
{ &delete_before, 0, sizeof(delete_before) },
{ &csum_length, 0, sizeof(csum_length) },
{ &checksum_len, 0, sizeof(checksum_len) },
{ &logfile_name, 1, 0 },
{ &ignore_existing, 0, sizeof(ignore_existing) },
{ &batch_gen_fd, 0, sizeof(batch_gen_fd) },
{ &bind_address, 1, 0 },
{ &keep_dirlinks, 0, sizeof(keep_dirlinks) },
{ &force_delete, 0, sizeof(force_delete) },
{ &logfile_format_has_o_or_i, 0, sizeof(logfile_format_has_o_or_i) },
{ &am_daemon, 0, sizeof(am_daemon) },
{ &files_from, 1, 0 },
{ &preserve_hard_links, 0, sizeof(preserve_hard_links) },
{ &tmpdir, 1, 0 },
{ &updating_basis_file, 0, sizeof(updating_basis_file) },
{ &log_got_error, 0, sizeof(log_got_error) },
{ &copy_dirlinks, 0, sizeof(copy_dirlinks) },
{ &chmod_modes, 1, sizeof(*chmod_modes) },
{ &write_batch_monitor_out, 0, sizeof(write_batch_monitor_out) },
{ &ignore_timeout, 0, sizeof(ignore_timeout) },
{ &append_mode, 0, sizeof(append_mode) },
{ &config_file, 1, 0 },
{ &no_detach, 0, sizeof(no_detach) },
{ &basis_dir_cnt, 0, sizeof(basis_dir_cnt) },
{ &delete_after, 0, sizeof(delete_after) },
{ &read_batch, 0, sizeof(read_batch) },
{ &bwlimit, 0, sizeof(bwlimit) },
{ NULL, 0, 0 }
 };
